CREATE TABLE DIRECTORS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE FILM_DIRECTORS (
    FILM_ID INT NOT NULL,
    DIRECTOR_ID INT NOT NULL,
    PRIMARY KEY (FILM_ID, DIRECTOR_ID),
    FOREIGN KEY (FILM_ID) REFERENCES FILMS(ID) ON DELETE CASCADE,
    FOREIGN KEY (DIRECTOR_ID) REFERENCES DIRECTORS(ID) ON DELETE CASCADE
);